// Purpose: Verify hysteresis, exact cache invalidation, deletion semantics and bounded polling.
import test from 'node:test';
import assert from 'node:assert/strict';
import { scan, watch } from '../src/index.mjs';
const policy = { id: 'risk', condition: 'launch blocked', model: 'jev-1.13.0', onThreshold: .8, offThreshold: .2 };
const items = p => [{ id: 'one', text: String(p) }];
const evaluator = async item => ({ probability: Number(item.text) });
test('dead band retains state and marks uncertainty until opposite threshold', async () => { let previous; const states = []; const changes = []; for (const p of [.5, .9, .6, .1]) { previous = await scan(items(p), policy, { evaluator, previous }); states.push(previous.items[0].state); changes.push(previous.transitions.length); } assert.deepEqual(states, ['unknown', 'true', 'true', 'false']); assert.deepEqual(changes, [0, 1, 0, 1]); });
test('unchanged source is reused with no evaluator call', async () => { const previous = await scan(items(.9), policy, { evaluator }); const r = await scan(items(.9), policy, { previous, evaluator: () => { throw new Error('should not call'); } }); assert.equal(r.cached, 1); assert.equal(r.evaluated, 0); assert.equal(r.transitions.length, 0); });
test('policy changes reject old caches and item removal is explicit', async () => { const previous = await scan(items(.9), policy, { evaluator }); await assert.rejects(scan(items(.9), { ...policy, condition: 'other' }, { evaluator, previous }), /another policy/); const r = await scan([], policy, { evaluator, previous }); assert.deepEqual(r.transitions, [{ id: 'one', from: 'true', to: 'removed' }]); });
test('duplicate ids, invalid thresholds and corrupted probabilities reject', async () => { await assert.rejects(scan([...items(.9), ...items(.1)], policy, { evaluator }), /unique/); await assert.rejects(scan([], { ...policy, offThreshold: .9 }, { evaluator }), /Threshold/); await assert.rejects(scan(items(.9), policy, { evaluator: async () => ({ probability: 2 }) }), /probability/); });
test('failed scan does not mutate previous checkpoint', async () => { const previous = await scan(items(.9), policy, { evaluator }); const copy = structuredClone(previous); await assert.rejects(scan(items(.1), policy, { previous, evaluator: async () => { throw new Error('provider down'); } }), /provider down/); assert.deepEqual(previous, copy); });
test('polling reloads source and preserves checkpoints', async () => { let n = 0; const result = []; for await (const r of watch(async () => items(n++ ? .1 : .9), policy, { evaluator, iterations: 2, intervalMs: 10 })) result.push(r); assert.equal(result[1].transitions[0].to, 'false'); });
test('source and evaluator deadlines propagate', async () => { await assert.rejects(scan(items(.9), policy, { evaluator: () => new Promise(() => {}), timeoutMs: 5 }), /deadline/); await assert.rejects(async () => { for await (const _ of watch(() => new Promise(() => {}), policy, { evaluator, timeoutMs: 5 })) {} }, /deadline/); });
